name: Lineage Builder

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config.env
      - name: Setup Tools
        run: |
          sudo apt update && sudo apt install repo
          mkdir build; cd build
          repo init -u "${{ steps.config.outputs.lineage_repo }}" -b "${{ steps.config.outputs.lineage_branch }}" --git-lfs
          git clone "${{ steps.config.outputs.tool_build_repo }}" lineage_build_unified -b "${{ steps.config.outputs.tool_branch }}"
          git clone "${{ steps.config.outputs.tool_patch_repo }}" lineage_patches_unified -b "${{ steps.config.outputs.tool_branch }}"
      - name: Build
        run: |
          bash lineage_build_unified/buildbot_unified.sh "${{ steps.config.outputs.build_type_command }}" "${{ steps.config.outputs.build_arch }}"
